apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
        - name: workers
          image: otsofts/workers
          env:
            - name: REDIS_HOST
              value: workers-redis-srv